version: "3.9"
services:
  voting-site:
    image: voting-site:latest
    container_name: voting-site
    ports:
      - 8082:80
    depends_on:
      - voting-api
  voting-api:
    image: voting-api:latest
    container_name: voting-api
    ports:
      - 8081:8080
    environment:
      - SPRING_APPLICATION_JSON={"spring":{"redis":{"port":"6379","host":"redis-db"}}}
    depends_on:
      - redis-db
  redis-db:
    image: redis:alpine3.12
    ports:
      - 6379:6379
    container_name: redis-db
  voting-console:
    image: voting-console:latest
    container_name: voting-console
    depends_on:
      - postgres-db
      - redis-db
    environment:
      - SPRING_APPLICATION_JSON={"spring":{"datasource":{"url":"jdbc:postgresql://postgres-db:5432/postgres"},"redis":{"port":"6379","host":"redis-db"}}}
  postgres-db:
    image: postgres:alpine
    container_name: postgres-db
    environment:
      - POSTGRES_PASSWORD=Qwer1234
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    volumes:
      - type: bind
        source: ./Data/pgdata
        target: /var/lib/postgresql/data
  adminer:
    image: adminer
    ports:
      - 8090:8080
